GET https://snow.instructure.com/courses/1013058/assignments/15397389/submissions/2083026?preview=1&version=1
Authorization: Bearer {{$dotenv CANVAS_TOKEN}}

###
GET https://snow.instructure.com/api/v1/courses/1154759/assignments/16571735/submissions?per_page=100&include%5B%5D=user&include%5B%5D=submission_comments&include%5B%5D=rubric_assessment
Authorization: Bearer {{$dotenv CANVAS_TOKEN}}


###

GET https://snow.instructure.com/api/v1/courses/1013710
Authorization: Bearer {{$dotenv CANVAS_TOKEN}}
###

GET https://snow.instructure.com/api/v1/courses/1156075/assignments/16380543/submissions/3365682?include[]=submission_comments&include[]=rubric_assessment&include[]=full_rubric_assessment
Authorization: Bearer {{$dotenv CANVAS_TOKEN}}